version: '3.8'
name: fsh-api-infra
services:
  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - db-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80